apiVersion: v1
kind: Service
metadata:
  name: gke-test-service
spec:
  loadBalancerIP: 34.89.103.106
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spring-admin
