# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, workflow_dispatch]

env: 
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1 
  GKE_ZONE: europe-west2-a   # TODO: update to cluster zone
  DEPLOYMENT_NAME: spring-admin
  IMAGE: spring-admin
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
            # start of the google stuff
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        
        
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
          
      - name: ls
        run: |-
          ls
      - name: pwd
        run: |-
          pwd
          
    # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ls
          ./kustomize edit set image PROJECT_ID/IMAGE:TAG=$PROJECT_ID/$IMAGE:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
